FROM python:3.10-slim-buster

WORKDIR /app

COPY requirements.txt ./requirements.txt

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

# Expose port 8501
EXPOSE 8501

CMD ["python", "taskgpt/taskgpt_backend_algo.py"]